name: Sync dev with main

on:
  push:
    branches:
      - main

jobs:
  cascade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into dev
        run: |
          git fetch origin main
          git merge origin/main --no-edit

      - name: Push cascade merge
        run: git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
